import { PageHeader } from "antd"
import { redirect } from "next/dist/server/api-utils"
import Head from "next/head"
import Link from "next/link"
import styles from "../styles/PageLayout.module.css"

const PageLayout = ({ children, title = "NewsApp" }) => {
  return (
    <>
      <Head>
        <title>{title} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div>
          <Link href="/">🤖 newsApi</Link>
        </div>
        <div className={styles.link}>
          <Link href="/about">About</Link>
        </div>
      </header>
      <main>{children}</main>
    </>
  )
}

export default PageLayout
